# Generated by Django 2.2.16 on 2020-11-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
